sass:
  style: compressed

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "assets/img"
    values:
      image: true

# theme: jekyll-theme-minimalism
remote_theme: showzeng/Minimalism

# --- 网站信息设置 ---
# 下面填写你的博客标题
title: 2M的博客
# 下面填写你的网络常用名
name: 2M
# 下面填写你的座右铭或者是个性签名
description: var me = new Person();while(me.awake()) me.code();
# 你博客的 url 地址，比如：https://showzeng.github.io 或者是自定义的域名
url: https://laming.github.io/
# 在页尾的版权时间信息，比如：2016-2018，默认是 2018 年
copyright_time: 2020
# 标签页的 logo 及博客的头像，如果你想引用网络图片资源，就取消下面的注解，并填写图片资源的 url 地址
# 或者，推荐的做法是将这两个图片资源下载到本地的 /assets/img/ 文件夹下，且图片名必须命名为 favicon 和 avatar
# favicon:
# avatar:
# --- 网站信息设置 ---

# --- 文章列表页 ---
# 文章列表是否显示摘要
show_excerpt: true
# --- 文章页 ---

# --- 社交链接 ---
# 取消下面的注解，并填写相应的你要开启的社交链接
#twitter: https://twitter.com/showzeng
#weibo: https://weibo.com/varen5201314
github: https://github.com/LAming
# 邮件地址前面带上 mailto:
email: mailto:460411490@qq.com
# RSS 订阅
rss: true
# --- 社交链接 ---

plugins:
  - rouge
  - kramdown
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji

exclude:
  - script
  - docs
  - vendor
  - Gemfile
  - Gemfile.lock
